/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const CartDetails = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCartItems' : IDL.Func([IDL.Text], [IDL.Vec(CartDetails)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'init' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CartDetails = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCartItems' : IDL.Func([IDL.Text], [IDL.Vec(CartDetails)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'init' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };